[package]
name = "stream"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
futures = "0.3.31"
test-case = "3.3.1"
tokio = { version = "1.45.0", features = ["full"] }
tokio-stream = "0.1.17"
